### ISSUE TITLE
MVP & Schema Review

### ISSUE THREAD

**Issue by vawhitehouse** [yangc95/Pintage#1]
## MVP
- [x] add days to dates
- [x] You'll likely want to prioritize boards/pins & discovery feed before the user profile
- [x] Users should be able to delete & edit boards/pins (we need CRUD functionality on at least on MVP)

## Schema
- [x] You won't need the `image_url` for pins - we'll be using Amazon Web Services (AWS)
- [x] Pins will need to track their title & description
- [x] Do boards need descriptions?
- [x] What can a user 'follow'? boards? users? both? `follows` needs a second foreign key for whatever that is. If they can follow boards and users, you'll want to make `follows` polymorphic. (We can talk about this when we meet one-on-one)

**Comment by yangc95** [comment]
I really appreciate the review input! 
I made adjustments except for the boards needing descriptions. I think boards only need a title with corresponding pin_id's.
The polymorphic follower table is something I anticipate to be a bit tricky but I can't wait for the one-on-one. 
Please let me know if there's anything else that may need changes. Thank you!
